// All site content. Bilingual.
const CONTENT = {
  en: {
    nav: {
      about: "About",
      stack: "Stack",
      experience: "Experience",
      work: "Work",
      writing: "Writing",
      contact: "Contact",
    },
    hero: {
      ticker: ["HO CHI MINH CITY · UTC+7", "AVAILABLE FOR LEAD ROLES", "REMOTE OK"],
      name1: "Nghia",
      name2: "Nguyen",
      tagline: "Senior II / Tech Lead",
      blurb_p1: "I build distributed systems that don't fall over — Go services running 1,000+ RPS, pipelines processing 100K+ events/hour, teams that ship.",
      blurb_p2: "Currently Senior II at TrueProfit. Heading toward Tech Lead — leading architecture, mentoring engineers, owning outcomes.",
      cta1: "View Work",
      cta2: "Get In Touch",
      cta3: "Download CV",
    },
    marquee: [
      "GO", "•", "DISTRIBUTED SYSTEMS", "•", "POSTGRES", "•", "KAFKA", "•",
      "KUBERNETES", "•", "SYSTEM DESIGN", "•", "TEAM LEADERSHIP", "•",
      "EVENT-DRIVEN", "•", "OBSERVABILITY", "•", "STARROCKS", "•",
    ],
    about: {
      label: "/01 — ABOUT",
      h2: ["Engineer.", "Leader.", "Builder."],
      p1: "I'm an <b>engineering leader</b> with 7+ years building distributed systems, APIs, and data pipelines across e-commerce, cybersecurity, and enterprise software.",
      p2: "Promoted to <b>Team Lead</b> within months at Hitachi Vantara. Today I'm <b>Senior II / Sub-Lead</b> at TrueProfit, heading toward Tech Lead. I lead architecture decisions, mentor engineers, and own outcomes — not just write code.",
      p3: "My background is unconventional. I trained as an <b>aerospace engineer</b> through the elite Franco-Vietnamese PFIEV program at HCMUT — equivalent to a Master's. That mindset of <em>precision, systems thinking, and the cost of being wrong</em> shows up in every system I design.",
    },
    stats: [
      { num: "7+", cap: "Years engineering" },
      { num: "1K+", cap: "RPS in production", accent: true },
      { num: "100K", cap: "Events/hr processed" },
      { num: "6", cap: "Engineers led" },
    ],
    skills: {
      label: "/02 — STACK",
      h2: "What I reach for.",
      groups: [
        { title: "Languages", count: "5", items: [{ n: "Go", hot: true }, "Python", "TypeScript", "Java", "Node.js"] },
        { title: "Databases", count: "7", items: [{ n: "PostgreSQL", hot: true }, "MongoDB", "Redis", "StarRocks", "MySQL", "BigQuery", "SQLite"] },
        { title: "Infrastructure", count: "7", items: [{ n: "Kubernetes", hot: true }, "Docker", "AWS", "Terraform", "ArgoCD", "Nginx", "CI/CD"] },
        { title: "Messaging", count: "2", items: [{ n: "Kafka", hot: true }, "RabbitMQ"] },
        { title: "Architecture", count: "6", items: [{ n: "System Design", hot: true }, "Microservices", "Event-Driven", "DDD/CQRS", "gRPC", "GraphQL"] },
        { title: "Observability", count: "4", items: [{ n: "OpenTelemetry", hot: true }, "Grafana", "Prometheus", "Structured Logs"] },
      ],
    },
    experience: {
      label: "/03 — TRAJECTORY",
      h2: "Where I've been.",
      rows: [
        { when: "Jul 2024 — Now", role_main: "Senior Engineer II", role_sub: "/ Sub-Lead", co: "TrueProfit (FireGroup)", ind: "E-COMMERCE ANALYTICS · GO", badge: "PRODUCT OF THE YEAR" },
        { when: "Jul 2024 — Jun 2025", role_main: "Senior Engineer", role_sub: "/ Tech Lead", co: "Source Of Asia", ind: "ASSET MANAGEMENT · ENTERPRISE", badge: "LED FROM SCRATCH" },
        { when: "Nov 2022 — Jun 2024", role_main: "Senior Engineer", role_sub: "", co: "ECQ Vietnam", ind: "CYBERSECURITY · VN/TH/SG" },
        { when: "Apr 2022 — Nov 2022", role_main: "Senior Engineer", role_sub: "", co: "Sendo (FPT Group)", ind: "E-COMMERCE · CHECKOUT/CART" },
        { when: "Jan 2021 — Apr 2022", role_main: "Team Leader", role_sub: "/ Full-Stack", co: "Hitachi Vantara", ind: "ENTERPRISE · LED 6 ENGINEERS", badge: "BEST PERFORMANCE 2021" },
        { when: "Jun 2020 — Dec 2020", role_main: "Backend Engineer", role_sub: "", co: "Amaris Consulting", ind: "JAVA · MICROSERVICES" },
        { when: "Jan 2019 — Jun 2020", role_main: "Junior Developer", role_sub: "", co: "TMA Solutions", ind: "FIRST GIG · JAVA/PYTHON" },
      ],
    },
    work: {
      label: "/04 — SELECTED WORK",
      h2: "Things I built.",
      featuredBadge: "FEATURED CASE STUDY",
      statusLabels: { dev: "IN DEV", shipped: "SHIPPED" },
      featured: {
        meta: "2024 — 2025 · TECH LEAD · BUILT FROM SCRATCH",
        title1: "SOA Asset Management.",
        title2: "Millions of trucks, containers, machines —",
        title3: "one platform.",
        lede: "Led end-to-end build of a large-scale Asset Management Platform from <em>blank repo to enterprise audit</em> in twelve months. I designed core architecture, schemas, CI/CD; resolved nasty concurrency bugs in production; passed enterprise security and performance audits on the first try.",
        specs: [
          { k: "Scale", v: "Millions" },
          { k: "Stack", v: "Go · PG" },
          { k: "Outcome", v: "Shipped" },
          { k: "Audit", v: "Passed" },
        ],
        stack: ["Go", "PostgreSQL", "Docker", "ArgoCD", "Cloud Infra", "DDD"],
      },
      others: [
        { status: "shipped", name: "TrueProfit", role: "SR. ENGINEER II · CURRENT", desc: "Real-time Shopify analytics — 100K+ data points/hour, 1K+ RPS Go services. Designed in-house ad analytics pipelines. Product of the Year.", stack: ["Go", "MongoDB", "Kafka", "K8s", "StarRocks", "AWS Lambda"] },
        { status: "dev", name: "Cơm Tấm Má Tư", role: "SIDE PROJECT · WITH FAMILY", desc: "Full-stack restaurant ops for a Vietnamese rice family business — POS, KDS, real-time orders, multi-branch. Solo build on weekends, helping mom & dad scale.", stack: ["Next.js 16", "React 19", "Supabase", "TS"] },
        { status: "shipped", name: "ECQ Cybersec", role: "SR. ENGINEER", desc: "Backend services for cybersecurity products across VN, TH, SG. Tech-stack and DB design decisions. Resolved long-standing prod issues.", stack: ["Go", "PostgreSQL", "Redis", "Microservices"] },
        { status: "shipped", name: "Sendo Checkout", role: "SR. ENGINEER · CUSTOMER SQUAD", desc: "Core services for one of VN's top e-commerce platforms. Product, Cart, PayLater, Checkout. Performance work resolving bottlenecks at scale.", stack: ["Go", "MySQL", "Redis", "Kafka"] },
      ],
    },
    writing: {
      label: "/05 — WRITING",
      h2: "Thinking out loud.",
      sub: "Technical writing on Go, distributed systems, and engineering.",
      posts: [
        { date: "APR 2026", title: "From 100M Stuck Messages to Zero OOM", sub: "A 7-month war with a Go event pipeline. 50K → 128 goroutines, 98% memory reduction.", read: "15 MIN", url: "/blog/kafka-oom-pipeline.html" },
        { date: "APR 2026", title: "Rewriting Revenue Calculation From Source of Truth", sub: "Fixing ~94% revenue accuracy to 100% by recalculating from raw Shopify data. The reconciliation job got rejected — but the fix was bulletproof.", read: "13 MIN", url: "/blog/revenue-reconciliation-fix.html" },
      ],
      footer: "More incoming — system design notes, Postgres deep dives, founder-engineer logs.",
    },
    education: {
      label: "/06 — BACKGROUND",
      h2: "Where it started.",
      items: [
        { when: "2012 — 2020", title: "Mechanical / Aerospace Engineering", school: "HCMUT · PFIEV (Franco-Vietnamese elite track)", desc: "Master's-equivalent program with French engineering schools. Taught precision, systems thinking, and the cost of being wrong." },
        { when: "2009 — 2012", title: "Specialized High School", school: "Quang Trung Specialized · HCMC", desc: "Competitive STEM program." },
      ],
    },
    contact: {
      label: "/07 — CONTACT",
      h2_a: "Let's",
      h2_b: "talk.",
      blurb: "Open to senior / lead roles, technical advisory, and interesting collaborations. Replies within 24 hours.",
      links: [
        { k: "EMAIL", v: "ngocnghia128@gmail.com", href: "mailto:ngocnghia128@gmail.com" },
        { k: "LINKEDIN", v: "/in/nghia-nguyen-baab48223", href: "https://linkedin.com/in/nghia-nguyen-baab48223" },
        { k: "GITHUB", v: "@nghiack7", href: "https://github.com/nghiack7" },
        { k: "TELEGRAM", v: "@nghia_ck7", href: "https://t.me/nghia_ck7" },
        { k: "PHONE", v: "+84 794 788 363", href: "tel:+84794788363" },
      ],
    },
    foot: { left: "© 2026 Nghia Nguyen.", mid: "Built with intent.", right: "v2.0" },
    chat: {
      name: "Ask Nghia (AI)",
      stat: "● ONLINE — REPLIES IN ~2S",
      foot: "POWERED BY CLAUDE · NOT LIVE NGHIA",
      welcome: "Hey 👋 I'm an AI trained on Nghia's experience — ask me about his work, stack, availability, or technical opinions.",
      suggestions: [
        "What's he working on now?",
        "Is he open to remote roles?",
        "Why Go over Java?",
        "Tell me about SOA project",
      ],
      placeholder: "Ask anything about Nghia…",
      error: "Hmm, can't reach the AI right now. Try email instead: ngocnghia128@gmail.com",
    },
  },

  vi: {
    nav: {
      about: "Giới thiệu",
      stack: "Công nghệ",
      experience: "Kinh nghiệm",
      work: "Dự án",
      writing: "Bài viết",
      contact: "Liên hệ",
    },
    hero: {
      ticker: ["TP. HỒ CHÍ MINH · UTC+7", "ĐANG MỞ CƠ HỘI LEAD", "NHẬN REMOTE"],
      name1: "Nghĩa",
      name2: "Nguyễn",
      tagline: "Senior II / Tech Lead",
      blurb_p1: "Tôi xây các hệ phân tán chạy ổn định dưới tải thật — Go services 1.000+ RPS, pipeline xử lý 100K+ sự kiện/giờ, đội ngũ ship đều đặn.",
      blurb_p2: "Hiện là Senior II tại TrueProfit. Hướng đến Tech Lead — dẫn dắt kiến trúc, kèm cặp kỹ sư, và chịu trách nhiệm cho kết quả cuối.",
      cta1: "Xem Dự Án",
      cta2: "Liên Hệ",
      cta3: "Tải CV",
    },
    marquee: [
      "GO", "•", "DISTRIBUTED SYSTEMS", "•", "POSTGRES", "•", "KAFKA", "•",
      "KUBERNETES", "•", "SYSTEM DESIGN", "•", "TEAM LEADERSHIP", "•",
      "EVENT-DRIVEN", "•", "OBSERVABILITY", "•", "STARROCKS", "•",
    ],
    about: {
      label: "/01 — GIỚI THIỆU",
      h2: ["Kỹ sư.", "Người dẫn dắt.", "Người xây."],
      p1: "Tôi là <b>engineering leader</b> với hơn 7 năm xây các hệ phân tán, API và data pipeline cho e-commerce, an ninh mạng và phần mềm doanh nghiệp.",
      p2: "Được thăng <b>Team Lead</b> chỉ sau vài tháng tại Hitachi Vantara. Hiện là <b>Senior II / Sub-Lead</b> tại TrueProfit, đang tiến đến Tech Lead. Tôi dẫn dắt quyết định kiến trúc, kèm cặp kỹ sư và chịu trách nhiệm cho kết quả — không chỉ viết code.",
      p3: "Xuất thân của tôi hơi khác. Tôi học <b>kỹ sư hàng không</b> qua chương trình elite Pháp-Việt PFIEV tại Bách Khoa TP.HCM — tương đương Thạc sĩ. Tư duy về <em>sự chính xác, cách nghĩ theo hệ thống và cái giá của một quyết định sai</em> theo tôi vào mọi hệ thống tôi thiết kế.",
    },
    stats: [
      { num: "7+", cap: "Năm kinh nghiệm" },
      { num: "1K+", cap: "RPS trên production", accent: true },
      { num: "100K", cap: "Sự kiện/giờ xử lý" },
      { num: "6", cap: "Kỹ sư đã dẫn dắt" },
    ],
    skills: {
      label: "/02 — CÔNG NGHỆ",
      h2: "Những thứ tôi hay dùng.",
      groups: [
        { title: "Ngôn ngữ", count: "5", items: [{ n: "Go", hot: true }, "Python", "TypeScript", "Java", "Node.js"] },
        { title: "Cơ sở dữ liệu", count: "7", items: [{ n: "PostgreSQL", hot: true }, "MongoDB", "Redis", "StarRocks", "MySQL", "BigQuery", "SQLite"] },
        { title: "Hạ tầng", count: "7", items: [{ n: "Kubernetes", hot: true }, "Docker", "AWS", "Terraform", "ArgoCD", "Nginx", "CI/CD"] },
        { title: "Hàng đợi", count: "2", items: [{ n: "Kafka", hot: true }, "RabbitMQ"] },
        { title: "Kiến trúc", count: "6", items: [{ n: "System Design", hot: true }, "Microservices", "Event-Driven", "DDD/CQRS", "gRPC", "GraphQL"] },
        { title: "Quan sát hệ thống", count: "4", items: [{ n: "OpenTelemetry", hot: true }, "Grafana", "Prometheus", "Structured Logs"] },
      ],
    },
    experience: {
      label: "/03 — HÀNH TRÌNH",
      h2: "Những nơi đã đi qua.",
      rows: [
        { when: "07/2024 — Hiện tại", role_main: "Senior Engineer II", role_sub: "/ Sub-Lead", co: "TrueProfit (FireGroup)", ind: "E-COMMERCE ANALYTICS · GO", badge: "SẢN PHẨM CỦA NĂM" },
        { when: "07/2024 — 06/2025", role_main: "Senior Engineer", role_sub: "/ Tech Lead", co: "Source Of Asia", ind: "ASSET MANAGEMENT · ENTERPRISE", badge: "DẪN DẮT TỪ ĐẦU" },
        { when: "11/2022 — 06/2024", role_main: "Senior Engineer", role_sub: "", co: "ECQ Vietnam", ind: "CYBERSECURITY · VN/TH/SG" },
        { when: "04/2022 — 11/2022", role_main: "Senior Engineer", role_sub: "", co: "Sendo (FPT Group)", ind: "E-COMMERCE · CHECKOUT/CART" },
        { when: "01/2021 — 04/2022", role_main: "Team Leader", role_sub: "/ Full-Stack", co: "Hitachi Vantara", ind: "ENTERPRISE · DẪN DẮT 6 KỸ SƯ", badge: "BEST PERFORMANCE 2021" },
        { when: "06/2020 — 12/2020", role_main: "Backend Engineer", role_sub: "", co: "Amaris Consulting", ind: "JAVA · MICROSERVICES" },
        { when: "01/2019 — 06/2020", role_main: "Junior Developer", role_sub: "", co: "TMA Solutions", ind: "DỰ ÁN ĐẦU TIÊN · JAVA/PYTHON" },
      ],
    },
    work: {
      label: "/04 — DỰ ÁN NỔI BẬT",
      h2: "Những thứ đã xây.",
      featuredBadge: "CASE STUDY NỔI BẬT",
      statusLabels: { dev: "ĐANG LÀM", shipped: "ĐÃ SHIP" },
      featured: {
        meta: "2024 — 2025 · TECH LEAD · XÂY TỪ ĐẦU",
        title1: "SOA Asset Management.",
        title2: "Hàng triệu xe tải, container, máy móc —",
        title3: "một nền tảng.",
        lede: "Dẫn dắt xây platform Asset Management quy mô lớn, từ <em>repo trống đến audit enterprise</em> trong 12 tháng. Tôi thiết kế kiến trúc lõi, schema, CI/CD; xử lý các lỗi concurrency khó trong production; vượt qua audit bảo mật và hiệu năng enterprise ngay lần đầu.",
        specs: [
          { k: "Quy mô", v: "Hàng triệu" },
          { k: "Stack", v: "Go · PG" },
          { k: "Kết quả", v: "Đã ship" },
          { k: "Audit", v: "Đạt" },
        ],
        stack: ["Go", "PostgreSQL", "Docker", "ArgoCD", "Cloud Infra", "DDD"],
      },
      others: [
        { status: "shipped", name: "TrueProfit", role: "SR. ENGINEER II · HIỆN TẠI", desc: "Analytics real-time cho Shopify — 100K+ data point/giờ, 1K+ RPS với Go. Thiết kế pipeline ad analytics in-house. Sản phẩm của năm.", stack: ["Go", "MongoDB", "Kafka", "K8s", "StarRocks", "AWS Lambda"] },
        { status: "dev", name: "Cơm Tấm Má Tư", role: "DỰ ÁN PHỤ · CÙNG GIA ĐÌNH", desc: "Hệ thống vận hành cho quán cơm tấm gia đình — POS, KDS, đơn real-time, nhiều chi nhánh. Tự xây cuối tuần, giúp ba mẹ scale.", stack: ["Next.js 16", "React 19", "Supabase", "TS"] },
        { status: "shipped", name: "ECQ Cybersec", role: "SR. ENGINEER", desc: "Các backend service cho sản phẩm an ninh mạng tại VN, TH, SG. Quyết định tech stack và thiết kế DB. Xử lý dứt điểm các lỗi production tồn đọng lâu.", stack: ["Go", "PostgreSQL", "Redis", "Microservices"] },
        { status: "shipped", name: "Sendo Checkout", role: "SR. ENGINEER · CUSTOMER SQUAD", desc: "Các service lõi cho một trong những sàn TMĐT lớn nhất VN. Product, Cart, PayLater, Checkout. Tối ưu hiệu năng, xử lý nghẽn cổ chai ở quy mô lớn.", stack: ["Go", "MySQL", "Redis", "Kafka"] },
      ],
    },
    writing: {
      label: "/05 — BÀI VIẾT",
      h2: "Suy nghĩ thành chữ.",
      sub: "Viết về Go, hệ phân tán và nghề kỹ sư.",
      posts: [
        { date: "04/2026", title: "Từ 100M Tin Nhắn Kẹt Đến Zero OOM", sub: "Cuộc chiến 7 tháng với một Go event pipeline. 50K → 128 goroutine, giảm 98% bộ nhớ.", read: "15 PHÚT", url: "/blog/kafka-oom-pipeline.html" },
        { date: "04/2026", title: "Viết Lại Revenue Calculation Từ Source of Truth", sub: "Đưa độ chính xác doanh thu từ ~94% lên 100% bằng cách tính lại từ Shopify raw data. Job reconciliation bị reject — nhưng bản fix thì bulletproof.", read: "13 PHÚT", url: "/blog/revenue-reconciliation-fix.html" },
      ],
      footer: "Sắp ra thêm — ghi chú system design, đào sâu Postgres, nhật ký founder-engineer.",
    },
    education: {
      label: "/06 — NỀN TẢNG",
      h2: "Nơi bắt đầu.",
      items: [
        { when: "2012 — 2020", title: "Cơ khí / Hàng không Vũ trụ", school: "Bách Khoa TP.HCM · PFIEV (Pháp-Việt elite)", desc: "Chương trình tương đương Thạc sĩ với các trường kỹ thuật Pháp. Dạy tôi sự chính xác, cách nghĩ theo hệ thống và cái giá của một quyết định sai." },
        { when: "2009 — 2012", title: "THPT Chuyên", school: "Chuyên Quang Trung · TP.HCM", desc: "Chương trình STEM cạnh tranh." },
      ],
    },
    contact: {
      label: "/07 — LIÊN HỆ",
      h2_a: "Cùng",
      h2_b: "trò chuyện.",
      blurb: "Sẵn sàng cho vai trò senior / lead, tư vấn kỹ thuật và các dự án hợp tác thú vị. Phản hồi trong vòng 24 giờ.",
      links: [
        { k: "EMAIL", v: "ngocnghia128@gmail.com", href: "mailto:ngocnghia128@gmail.com" },
        { k: "LINKEDIN", v: "/in/nghia-nguyen-baab48223", href: "https://linkedin.com/in/nghia-nguyen-baab48223" },
        { k: "GITHUB", v: "@nghiack7", href: "https://github.com/nghiack7" },
        { k: "TELEGRAM", v: "@nghia_ck7", href: "https://t.me/nghia_ck7" },
        { k: "PHONE", v: "+84 794 788 363", href: "tel:+84794788363" },
      ],
    },
    foot: { left: "© 2026 Nghĩa Nguyễn.", mid: "Xây có chủ đích.", right: "v2.0" },
    chat: {
      name: "Hỏi Nghĩa (AI)",
      stat: "● ONLINE — TRẢ LỜI ~2S",
      foot: "POWERED BY CLAUDE · KHÔNG PHẢI NGHĨA THẬT",
      welcome: "Chào bạn 👋 Mình là AI được huấn luyện trên thông tin của Nghĩa — hỏi mình về công việc, stack, lịch trống hay quan điểm kỹ thuật của Nghĩa nhé.",
      suggestions: [
        "Đang làm gì hiện tại?",
        "Có nhận remote không?",
        "Tại sao chọn Go thay Java?",
        "Kể về dự án SOA",
      ],
      placeholder: "Hỏi gì về Nghĩa…",
      error: "Hmm, không kết nối được AI. Email Nghĩa nhé: ngocnghia128@gmail.com",
    },
  },
};

window.CONTENT = CONTENT;
